image: "virgilbugnariu/frilensar_build_deploy"

variables:
  NODE_ENV: production

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - node_modules/

# Deploy on prod
deploy:prodv2:
  only:
    - develop
  script:
    - mkdir /root/.ssh
    - touch /root/.ssh/known_hosts
    - chmod 600 /root/.ssh
    - echo "[$SSH_HOST]:$SSH_PORT $SSH_FINGERPRINT" >> /root/.ssh/known_hosts
    - chmod 600 /root/.ssh/known_hosts
    - chmod 400 $SSH_KEY
    - npm install --silent
    - npm run build
    - tar -czf release.tar.gz '.next/' 'public/' 'server.js' 'package.json' 'package-lock.json'
    - scp -P $SSH_PORT -i "$SSH_KEY" ./release.tar.gz $SSH_USER@$SSH_HOST:frilensar-app/
    - ssh -p $SSH_PORT -i $SSH_KEY $SSH_USER@$SSH_HOST "cd frilensar-app && rm -rf .next/ && rm -rf public/ && rm -f server.js && rm -f package.json && rm -f package-lock.json && tar -xzf release.tar.gz && rm release.tar.gz; touch tmp/restart.txt"
  artifacts:
    paths:
      - release.tar.gz
    expire_in: 1 day
